/** Generates seed/catalog.sql (applied on every deploy; idempotent) from data/decks/*.csv. Usage: npx tsx scripts/csv-to-sql.ts */
import { writeFileSync } from "node:fs";
import { csvToSql } from "./lib/csv";
import { readDeck, readIndex } from "./lib/decks";

let sql = "-- Generated by scripts/csv-to-sql.ts. Do not edit by hand.\n";
for (const d of readIndex()) {
  const rows = readDeck(d.file);
  sql += csvToSql({ slug: d.slug, titleRu: d.titleRu, titleEn: d.titleEn, level: d.level }, rows);
  console.log(`${d.slug}: ${rows.length} words`);
}
writeFileSync("seed/catalog.sql", sql);
